# File              : uninstall.yml
# Author            : Rustam Khafizov <super.rustamm@gmail.com>
# Date              : 08.09.2020
# Last Modified Date: 08.09.2020
# Last Modified By  : Rustam Khafizov <super.rustamm@gmail.com>

---
